cmake_minimum_required(VERSION 3.10)
project(Exercise1)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
include_directories(include)
file(GLOB SOURCES "src/*.cpp")
add_executable(app.out ${SOURCES})
include(FetchContent)
FetchContent_Declare(googletest URL https://github.com/google/googletest/archive/refs/tags/v1.15.2.zip)
set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(googletest)
add_executable(tests.out tests/RecommendationTests.cpp src/RecommendationLogic.cpp )
target_include_directories(tests.out PUBLIC include)
target_link_libraries(tests.out gtest gtest_main)
include_directories(include)