services:
  # C++ Server Service
  cpp-server:
    build:
      context: .
      dockerfile: Dockerfile.server # dockerfile usage for C++ server
    ports:
      - "8000:8000" # expose port 8000 for the C++ server
    networks:
      - app-network

  # cppGateway.js API Service
  cpp-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway # dockerfile usage for cppGateway.js API
    ports:
      - "8080:8080" # expose port 8080 for the cppGateway.js API
    environment:
      - CPP_SERVER_HOST=cpp-server # use the service name as the host to connect to the C++ server
      - CPP_SERVER_PORT=8000 # use the exposed port of the C++ server
    depends_on:
      - cpp-server # makes the cppGateway.js API wait for the C++ server to start first
    networks:
      - app-network

networks:
  app-network:
    driver: bridge