FROM python:3.10-slim

WORKDIR /app

COPY src/client.py ./src/

# Run the client script. It expects <server_ip> and <server_port> as arguments
ENTRYPOINT ["python3", "src/client.py"]
CMD ["localhost", "8000"]