version: '3.8'

services:
  # C++ Server Service
  cpp-server:
    build:
      context: .
      dockerfile: Dockerfile.server # dockerfile usage for C++ server
    ports:
      - "8000:8000" # expose port 8000 for the C++ server
    networks:
      - app-network

  # cppGateway.js API Service
  cpp-gateway:
    build:
      context: .
      dockerfile: Dockerfile # dockerfile usage for cppGateway.js API
    ports:
      - "8080:8080" # expose port 8080 for the cppGateway.js API
    environment:
      - CPP_SERVER_URL=http://cpp-server:8000 # environment variable for the cppGateway.js API to know where the C++ server is located
    depends_on:
      - cpp-server # makes the cppGateway.js API wait for the C++ server to start first
    networks:
      - app-network

networks:
  app-network:
    driver: bridge