FROM gcc:latest

WORKDIR /app

COPY src/ ./src/
COPY include/ ./include/
COPY data/ ./data/
COPY tests/ ./tests/
COPY *.txt ./

RUN cp include/*.h src/ 

# Deleting the main of the server so that won't be a collision
RUN rm -f src/main.cpp

RUN g++ -std=c++17 -Iinclude -Isrc src/*.cpp tests/*.cpp -o run_tests.exe

CMD ["./run_tests.exe"]